services:
  app:
    build: .
    container_name: h-links-app
    ports:
      - "8081:8080"
    volumes:
      - ./storage:/app/storage
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle:1521/XEPDB1
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      HLINKS_FFMPEG_COMMAND: ffmpeg
      OPENAI_API_KEY: ${OPENAI_API_KEY}

      HLINKS_STORAGE_TYPE: s3
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ap-northeast-2
      AWS_S3_BUCKET: amzn-hlinks-s3-bucket
    depends_on:
      oracle:
        condition: service_healthy