ALTER TABLE COMPETENCY_SCORE_HISTORY ADD (
    REFERENCE_TYPE VARCHAR2(50),
    REFERENCE_ID   NUMBER
);

CREATE INDEX IX_COMP_SCORE_HIST_REF
ON COMPETENCY_SCORE_HISTORY (
    USER_ID,
    COMPETENCY_ID,
    CALC_TYPE,
    REFERENCE_TYPE,
    REFERENCE_ID
);
