INSERT INTO COMPETENCY_ACTION_SCORE_POLICY (
    POLICY_ID,
    CALC_TYPE,
    COMPETENCY_ID,
    SCORE_DELTA
)
SELECT COMP_ACTION_SCORE_POLICY_SEQ.NEXTVAL, 'KCY_TEST_TAKEN', 3, 0.5
FROM DUAL
WHERE EXISTS (
    SELECT 1
    FROM COMPETENCY
    WHERE COMPETENCY_ID = 3
)
AND NOT EXISTS (
    SELECT 1
    FROM COMPETENCY_ACTION_SCORE_POLICY
    WHERE CALC_TYPE = 'KCY_TEST_TAKEN'
      AND COMPETENCY_ID = 3
);
