UPDATE SKILL
SET SKILL_CODE = 'INFRA'
WHERE SKILL_ID = 1
  AND SKILL_CODE IS NULL;

UPDATE SKILL
SET SKILL_CODE = 'SECURITY'
WHERE SKILL_ID = 2
  AND SKILL_CODE IS NULL;

UPDATE SKILL
SET SKILL_CODE = 'AI_LAB'
WHERE SKILL_ID = 3
  AND SKILL_CODE IS NULL;

UPDATE SKILL
SET SKILL_CODE = 'AX'
WHERE SKILL_ID = 4
  AND SKILL_CODE IS NULL;

UPDATE SKILL
SET SKILL_CODE = 'FRONTEND'
WHERE SKILL_ID = 5
  AND SKILL_CODE IS NULL;

UPDATE SKILL
SET SKILL_CODE = 'BACKEND'
WHERE SKILL_ID = 6
  AND SKILL_CODE IS NULL;

INSERT INTO SKILL (
    SKILL_ID,
    SKILL_NAME,
    PARENT_SKILL_ID,
    SKILL_TYPE,
    USE_YN,
    SKILL_CODE
)
SELECT 1001, 'Collaboration/Communication', NULL, 'CATEGORY', 'Y', 'COLLABORATION_COMMUNICATION'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SKILL WHERE SKILL_ID = 1001 OR SKILL_CODE = 'COLLABORATION_COMMUNICATION');

INSERT INTO SKILL (
    SKILL_ID,
    SKILL_NAME,
    PARENT_SKILL_ID,
    SKILL_TYPE,
    USE_YN,
    SKILL_CODE
)
SELECT 1002, 'Leadership/Management', NULL, 'CATEGORY', 'Y', 'LEADERSHIP_MANAGEMENT'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SKILL WHERE SKILL_ID = 1002 OR SKILL_CODE = 'LEADERSHIP_MANAGEMENT');

INSERT INTO SKILL (
    SKILL_ID,
    SKILL_NAME,
    PARENT_SKILL_ID,
    SKILL_TYPE,
    USE_YN,
    SKILL_CODE
)
SELECT 1003, 'Global/Language', NULL, 'CATEGORY', 'Y', 'GLOBAL_LANGUAGE'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SKILL WHERE SKILL_ID = 1003 OR SKILL_CODE = 'GLOBAL_LANGUAGE');

INSERT INTO SKILL (
    SKILL_ID,
    SKILL_NAME,
    PARENT_SKILL_ID,
    SKILL_TYPE,
    USE_YN,
    SKILL_CODE
)
SELECT 1004, 'Creative/Planning', NULL, 'CATEGORY', 'Y', 'CREATIVE_PLANNING'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SKILL WHERE SKILL_ID = 1004 OR SKILL_CODE = 'CREATIVE_PLANNING');

INSERT INTO SKILL (
    SKILL_ID,
    SKILL_NAME,
    PARENT_SKILL_ID,
    SKILL_TYPE,
    USE_YN,
    SKILL_CODE
)
SELECT 1101, 'Teamwork', 1001, 'SOFT', 'Y', 'TEAMWORK'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SKILL WHERE SKILL_ID = 1101 OR SKILL_CODE = 'TEAMWORK');

INSERT INTO SKILL (
    SKILL_ID,
    SKILL_NAME,
    PARENT_SKILL_ID,
    SKILL_TYPE,
    USE_YN,
    SKILL_CODE
)
SELECT 1102, 'Presentation', 1001, 'SOFT', 'Y', 'PRESENTATION'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SKILL WHERE SKILL_ID = 1102 OR SKILL_CODE = 'PRESENTATION');

INSERT INTO SKILL (
    SKILL_ID,
    SKILL_NAME,
    PARENT_SKILL_ID,
    SKILL_TYPE,
    USE_YN,
    SKILL_CODE
)
SELECT 1103, 'Communication', 1001, 'SOFT', 'Y', 'COMMUNICATION'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SKILL WHERE SKILL_ID = 1103 OR SKILL_CODE = 'COMMUNICATION');

INSERT INTO SKILL (
    SKILL_ID,
    SKILL_NAME,
    PARENT_SKILL_ID,
    SKILL_TYPE,
    USE_YN,
    SKILL_CODE
)
SELECT 1201, 'Leadership', 1002, 'SOFT', 'Y', 'LEADERSHIP'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SKILL WHERE SKILL_ID = 1201 OR SKILL_CODE = 'LEADERSHIP');

INSERT INTO SKILL (
    SKILL_ID,
    SKILL_NAME,
    PARENT_SKILL_ID,
    SKILL_TYPE,
    USE_YN,
    SKILL_CODE
)
SELECT 1202, 'Project Management', 1002, 'SOFT', 'Y', 'PROJECT_MANAGEMENT'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SKILL WHERE SKILL_ID = 1202 OR SKILL_CODE = 'PROJECT_MANAGEMENT');

INSERT INTO SKILL (
    SKILL_ID,
    SKILL_NAME,
    PARENT_SKILL_ID,
    SKILL_TYPE,
    USE_YN,
    SKILL_CODE
)
SELECT 1301, 'Language', 1003, 'GLOBAL', 'Y', 'LANGUAGE'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SKILL WHERE SKILL_ID = 1301 OR SKILL_CODE = 'LANGUAGE');

INSERT INTO SKILL (
    SKILL_ID,
    SKILL_NAME,
    PARENT_SKILL_ID,
    SKILL_TYPE,
    USE_YN,
    SKILL_CODE
)
SELECT 1302, 'Global IT', 1003, 'GLOBAL', 'Y', 'GLOBAL_IT'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SKILL WHERE SKILL_ID = 1302 OR SKILL_CODE = 'GLOBAL_IT');

INSERT INTO SKILL (
    SKILL_ID,
    SKILL_NAME,
    PARENT_SKILL_ID,
    SKILL_TYPE,
    USE_YN,
    SKILL_CODE
)
SELECT 1401, 'Planning/UX', 1004, 'PLANNING', 'Y', 'PLANNING_UX'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SKILL WHERE SKILL_ID = 1401 OR SKILL_CODE = 'PLANNING_UX');

INSERT INTO SKILL (
    SKILL_ID,
    SKILL_NAME,
    PARENT_SKILL_ID,
    SKILL_TYPE,
    USE_YN,
    SKILL_CODE
)
SELECT 1402, 'New Tech', 1004, 'TECH_TREND', 'Y', 'NEW_TECH'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SKILL WHERE SKILL_ID = 1402 OR SKILL_CODE = 'NEW_TECH');

INSERT INTO SKILL_COMPETENCY_SCORE (
    POLICY_ID,
    SKILL_ID,
    CALC_TYPE,
    COMPETENCY_ID,
    SCORE_DELTA
)
SELECT SKILL_COMPETENCY_SCORE_SEQ.NEXTVAL, policy.SKILL_ID, policy.CALC_TYPE, policy.COMPETENCY_ID, policy.SCORE_DELTA
FROM (
    SELECT 1 AS SKILL_ID, 'TECH_SPECIAL_COMPLETE' AS CALC_TYPE, 1 AS COMPETENCY_ID, 1.0 AS SCORE_DELTA FROM DUAL
    UNION ALL SELECT 2, 'TECH_SPECIAL_COMPLETE', 1, 1.0 FROM DUAL
    UNION ALL SELECT 3, 'TECH_SPECIAL_COMPLETE', 1, 1.0 FROM DUAL
    UNION ALL SELECT 3, 'AI_LECTURE_COMPLETE', 5, 1.2 FROM DUAL
    UNION ALL SELECT 4, 'TECH_SPECIAL_COMPLETE', 1, 1.0 FROM DUAL
    UNION ALL SELECT 4, 'AI_LECTURE_COMPLETE', 5, 1.2 FROM DUAL
    UNION ALL SELECT 5, 'TECH_SPECIAL_COMPLETE', 1, 1.0 FROM DUAL
    UNION ALL SELECT 6, 'TECH_SPECIAL_COMPLETE', 1, 1.0 FROM DUAL
    UNION ALL SELECT 1101, 'TEAMWORK_LECTURE_COMPLETE', 3, 1.2 FROM DUAL
    UNION ALL SELECT 1102, 'PRESENTATION_LECTURE_COMPLETE', 3, 0.8 FROM DUAL
    UNION ALL SELECT 1103, 'COMMUNICATION_LECTURE_COMPLETE', 4, 1.0 FROM DUAL
    UNION ALL SELECT 1201, 'LEADERSHIP_LECTURE_COMPLETE', 4, 1.2 FROM DUAL
    UNION ALL SELECT 1202, 'PROJECT_MANAGEMENT_COMPLETE', 4, 1.2 FROM DUAL
    UNION ALL SELECT 1301, 'LANGUAGE_LECTURE_COMPLETE', 6, 1.2 FROM DUAL
    UNION ALL SELECT 1302, 'GLOBAL_IT_LECTURE_COMPLETE', 6, 1.2 FROM DUAL
    UNION ALL SELECT 1401, 'PLANNING_UX_COMPLETE', 5, 1.0 FROM DUAL
    UNION ALL SELECT 1402, 'NEW_TECH_LECTURE_COMPLETE', 5, 1.0 FROM DUAL
) policy
WHERE EXISTS (
    SELECT 1
    FROM SKILL skill
    WHERE skill.SKILL_ID = policy.SKILL_ID
)
AND EXISTS (
    SELECT 1
    FROM COMPETENCY competency
    WHERE competency.COMPETENCY_ID = policy.COMPETENCY_ID
)
AND NOT EXISTS (
    SELECT 1
    FROM SKILL_COMPETENCY_SCORE existing
    WHERE existing.SKILL_ID = policy.SKILL_ID
      AND existing.CALC_TYPE = policy.CALC_TYPE
      AND existing.COMPETENCY_ID = policy.COMPETENCY_ID
);
