ALTER TABLE KCY_COFFEE_CHAT_REQUEST DROP CONSTRAINT CK_KCY_COFFEE_CHAT_STATUS;

ALTER TABLE KCY_COFFEE_CHAT_REQUEST ADD CONSTRAINT CK_KCY_COFFEE_CHAT_STATUS
    CHECK (STATUS IN ('REQUESTED', 'MAILED', 'ACCEPTED', 'REJECTED', 'CANCELED'));
