/* =========================================================
   H-Link Oracle DDL
   - Oracle 기준: VARCHAR2 / NUMBER / DATE / CLOB
   - ONLINE_COURSE, OFFLINE_COURSE는 COURSE와 1:1 상세 테이블
     이므로 별도 시퀀스 없이 COURSE_ID를 그대로 PK/FK로 사용
   ========================================================= */

/* =========================
   1. SEQUENCES
   ========================= */
CREATE SEQUENCE DEPARTMENT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE DEPARTMENT_SKILL_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE USERS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE JOB_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE POSITION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE ROLES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE USER_ROLE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE USER_INTEREST_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE COURSE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE COURSE_PREREQUISITE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE COURSE_CHAPTER_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SKILL_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE COURSE_SKILL_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE CHAPTER_SKILL_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE COURSE_APPLICATION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE COURSE_LEARNING_STATUS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE LEARNING_LOG_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE QUIZ_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE QUIZ_OPTION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE QUIZ_ATTEMPT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE QUIZ_ATTEMPT_ANSWER_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE COMPETENCY_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE COURSE_COMPETENCY_WEIGHT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE USER_COMPETENCY_SCORE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE COMPETENCY_SCORE_HISTORY_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE CAREER_DIAGNOSIS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE CAREER_TARGET_SKILL_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE LEVEL_TEST_QUESTION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE LEVEL_TEST_OPTION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE LEVEL_TEST_ANSWER_LOG_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE CAREER_RECOMMENDATION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE KCY_QUESTION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE KCY_OPTION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

/* =========================
   2. TABLES
   ========================= */
CREATE TABLE DEPARTMENT (
    DEPARTMENT_ID        NUMBER          NOT NULL,
    DEPARTMENT_NAME      VARCHAR2(100)   NOT NULL,
    PARENT_DEPARTMENT_ID NUMBER,
    USE_YN               VARCHAR2(1)     DEFAULT 'Y' NOT NULL,
    CREATED_AT           DATE            DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_DEPARTMENT PRIMARY KEY (DEPARTMENT_ID),
    CONSTRAINT CK_DEPT_USE_YN CHECK (USE_YN IN ('Y', 'N'))
);

CREATE TABLE JOB (
    JOB_ID       NUMBER         NOT NULL,
    JOB_NAME     VARCHAR2(100)  NOT NULL,
    DESCRIPTION  VARCHAR2(1000),
    USE_YN       VARCHAR2(1)    DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_JOB PRIMARY KEY (JOB_ID),
    CONSTRAINT CK_JOB_USE_YN CHECK (USE_YN IN ('Y', 'N'))
);

CREATE TABLE POSITION (
    POSITION_ID   NUMBER         NOT NULL,
    POSITION_NAME VARCHAR2(100)  NOT NULL,
    SORT_ORDER    NUMBER,
    USE_YN        VARCHAR2(1)    DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_POSITION PRIMARY KEY (POSITION_ID),
    CONSTRAINT CK_POSITION_USE_YN CHECK (USE_YN IN ('Y', 'N'))
);

CREATE TABLE ROLES (
    ROLE_ID    NUMBER        NOT NULL,
    ROLE_CODE  VARCHAR2(50)  NOT NULL,
    ROLE_NAME  VARCHAR2(100) NOT NULL,
    CONSTRAINT PK_ROLES PRIMARY KEY (ROLE_ID),
    CONSTRAINT UK_ROLES_CODE UNIQUE (ROLE_CODE)
);

CREATE TABLE SKILL (
    SKILL_ID        NUMBER        NOT NULL,
    SKILL_NAME      VARCHAR2(100) NOT NULL,
    PARENT_SKILL_ID NUMBER,
    SKILL_TYPE      VARCHAR2(50),
    USE_YN          VARCHAR2(1)   DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_SKILL PRIMARY KEY (SKILL_ID),
    CONSTRAINT CK_SKILL_USE_YN CHECK (USE_YN IN ('Y', 'N'))
);

CREATE TABLE USERS (
    USER_ID         NUMBER         NOT NULL,
    DEPARTMENT_ID   NUMBER,
    JOB_ID          NUMBER,
    POSITION_ID     NUMBER,
    LOGIN_ID        VARCHAR2(100)  NOT NULL,
    PASSWORD        VARCHAR2(255)  NOT NULL,
    NAME            VARCHAR2(100)  NOT NULL,
    EMAIL           VARCHAR2(255),
    PHONE           VARCHAR2(30),
    KCY_RESULT      VARCHAR2(100),
    FIRST_LOGIN_YN  VARCHAR2(1)    DEFAULT 'Y' NOT NULL,
    STATUS          VARCHAR2(30)   DEFAULT 'ACTIVE' NOT NULL,
    CREATED_AT      DATE           DEFAULT SYSDATE NOT NULL,
    UPDATED_AT      DATE,
    CONSTRAINT PK_USERS PRIMARY KEY (USER_ID),
    CONSTRAINT UK_USERS_LOGIN_ID UNIQUE (LOGIN_ID),
    CONSTRAINT UK_USERS_EMAIL UNIQUE (EMAIL),
    CONSTRAINT CK_USERS_FIRST_LOGIN CHECK (FIRST_LOGIN_YN IN ('Y', 'N'))
);

CREATE TABLE DEPARTMENT_SKILL (
    DEPARTMENT_SKILL_ID NUMBER       NOT NULL,
    DEPARTMENT_ID       NUMBER       NOT NULL,
    SKILL_ID            NUMBER       NOT NULL,
    USE_YN              VARCHAR2(1)  DEFAULT 'Y' NOT NULL,
    CREATED_AT          DATE         DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_DEPARTMENT_SKILL PRIMARY KEY (DEPARTMENT_SKILL_ID),
    CONSTRAINT UK_DEPT_SKILL UNIQUE (DEPARTMENT_ID, SKILL_ID),
    CONSTRAINT CK_DEPT_SKILL_USE_YN CHECK (USE_YN IN ('Y', 'N'))
);

CREATE TABLE USER_ROLE (
    USER_ROLE_ID NUMBER NOT NULL,
    USER_ID      NUMBER NOT NULL,
    ROLE_ID      NUMBER NOT NULL,
    CREATED_AT   DATE   DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_USER_ROLE PRIMARY KEY (USER_ROLE_ID),
    CONSTRAINT UK_USER_ROLE UNIQUE (USER_ID, ROLE_ID)
);

CREATE TABLE USER_INTEREST (
    USER_INTEREST_ID NUMBER NOT NULL,
    USER_ID          NUMBER NOT NULL,
    SKILL_ID         NUMBER NOT NULL,
    CREATED_AT       DATE   DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_USER_INTEREST PRIMARY KEY (USER_INTEREST_ID),
    CONSTRAINT UK_USER_INTEREST UNIQUE (USER_ID, SKILL_ID)
);

CREATE TABLE COURSE (
    COURSE_ID           NUMBER         NOT NULL,
    CREATED_BY          NUMBER,
    CATEGORY_TYPE       VARCHAR2(50)   NOT NULL,
    COURSE_TYPE         VARCHAR2(30)   NOT NULL,
    COURSE_TITLE        VARCHAR2(200)  NOT NULL,
    DESCRIPTION         CLOB,
    INSTRUCTOR_NAME     VARCHAR2(100),
    TOTAL_DURATION_TIME NUMBER,
    THUMBNAIL_URL       VARCHAR2(1000),
    CREATED_AT          DATE           DEFAULT SYSDATE NOT NULL,
    UPDATED_AT          DATE,
    CONSTRAINT PK_COURSE PRIMARY KEY (COURSE_ID),
    CONSTRAINT CK_COURSE_TYPE CHECK (COURSE_TYPE IN ('ONLINE', 'OFFLINE'))
);

CREATE TABLE ONLINE_COURSE (
    COURSE_ID           NUMBER         NOT NULL,
    COURSE_MATERIAL_URL VARCHAR2(1000),
    STATUS              VARCHAR2(30)   DEFAULT 'ACTIVE' NOT NULL,
    CONSTRAINT PK_ONLINE_COURSE PRIMARY KEY (COURSE_ID)
);

CREATE TABLE OFFLINE_COURSE (
    COURSE_ID         NUMBER         NOT NULL,
    CAPACITY          NUMBER,
    LOCATION          VARCHAR2(300),
    STATUS            VARCHAR2(30)   DEFAULT 'ACTIVE' NOT NULL,
    APPLY_START_DATE  DATE,
    APPLY_END_DATE    DATE,
    COURSE_START_DATE DATE,
    COURSE_END_DATE   DATE,
    CONSTRAINT PK_OFFLINE_COURSE PRIMARY KEY (COURSE_ID),
    CONSTRAINT CK_OFFLINE_CAPACITY CHECK (CAPACITY IS NULL OR CAPACITY >= 0)
);

CREATE TABLE COURSE_PREREQUISITE (
    PREREQUISITE_ID       NUMBER       NOT NULL,
    COURSE_ID             NUMBER       NOT NULL,
    PREREQUISITE_COURSE_ID NUMBER      NOT NULL,
    REQUIRED_YN           VARCHAR2(1)  DEFAULT 'Y' NOT NULL,
    CREATED_AT            DATE         DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_COURSE_PREREQ PRIMARY KEY (PREREQUISITE_ID),
    CONSTRAINT UK_COURSE_PREREQ UNIQUE (COURSE_ID, PREREQUISITE_COURSE_ID),
    CONSTRAINT CK_COURSE_PREREQ_REQ CHECK (REQUIRED_YN IN ('Y', 'N')),
    CONSTRAINT CK_COURSE_PREREQ_SELF CHECK (COURSE_ID <> PREREQUISITE_COURSE_ID)
);

CREATE TABLE COURSE_CHAPTER (
    CHAPTER_ID       NUMBER         NOT NULL,
    COURSE_ID        NUMBER         NOT NULL,
    CHAPTER_TITLE    VARCHAR2(200)  NOT NULL,
    CHAPTER_ORDER    NUMBER         NOT NULL,
    VIDEO_URL        VARCHAR2(1000),
    DURATION_SECONDS NUMBER,
    SUMMARY_TEXT     CLOB,
    TRANSCRIPT_TEXT  CLOB,
    AI_GENERATED_YN  VARCHAR2(1)    DEFAULT 'N' NOT NULL,
    USE_YN           VARCHAR2(1)    DEFAULT 'Y' NOT NULL,
    CREATED_AT       DATE           DEFAULT SYSDATE NOT NULL,
    UPDATED_AT       DATE,
    CONSTRAINT PK_COURSE_CHAPTER PRIMARY KEY (CHAPTER_ID),
    CONSTRAINT UK_COURSE_CHAPTER_ORDER UNIQUE (COURSE_ID, CHAPTER_ORDER),
    CONSTRAINT CK_CHAPTER_AI_YN CHECK (AI_GENERATED_YN IN ('Y', 'N')),
    CONSTRAINT CK_CHAPTER_USE_YN CHECK (USE_YN IN ('Y', 'N'))
);

CREATE TABLE COURSE_SKILL (
    COURSE_SKILL_ID NUMBER NOT NULL,
    COURSE_ID       NUMBER NOT NULL,
    SKILL_ID        NUMBER NOT NULL,
    WEIGHT          NUMBER DEFAULT 1 NOT NULL,
    CONSTRAINT PK_COURSE_SKILL PRIMARY KEY (COURSE_SKILL_ID),
    CONSTRAINT UK_COURSE_SKILL UNIQUE (COURSE_ID, SKILL_ID),
    CONSTRAINT CK_COURSE_SKILL_WEIGHT CHECK (WEIGHT >= 0)
);

CREATE TABLE CHAPTER_SKILL (
    CHAPTER_SKILL_ID NUMBER NOT NULL,
    CHAPTER_ID       NUMBER NOT NULL,
    SKILL_ID         NUMBER NOT NULL,
    WEIGHT           NUMBER DEFAULT 1 NOT NULL,
    CONSTRAINT PK_CHAPTER_SKILL PRIMARY KEY (CHAPTER_SKILL_ID),
    CONSTRAINT UK_CHAPTER_SKILL UNIQUE (CHAPTER_ID, SKILL_ID),
    CONSTRAINT CK_CHAPTER_SKILL_WEIGHT CHECK (WEIGHT >= 0)
);

CREATE TABLE COURSE_APPLICATION (
    APPLICATION_ID     NUMBER        NOT NULL,
    USER_ID            NUMBER        NOT NULL,
    COURSE_ID          NUMBER        NOT NULL,
    APPLICATION_STATUS VARCHAR2(30)  DEFAULT 'WAITING' NOT NULL,
    REJECT_REASON      VARCHAR2(1000),
    APPLIED_AT         DATE          DEFAULT SYSDATE NOT NULL,
    APPROVED_AT        DATE,
    APPROVED_BY        NUMBER,
    CONSTRAINT PK_COURSE_APPLICATION PRIMARY KEY (APPLICATION_ID),
    CONSTRAINT UK_COURSE_APPLICATION UNIQUE (USER_ID, COURSE_ID),
    CONSTRAINT CK_APP_STATUS CHECK (APPLICATION_STATUS IN ('WAITING', 'APPROVED', 'REJECTED', 'CANCELED'))
);

CREATE TABLE COURSE_LEARNING_STATUS (
    LEARNING_ID       NUMBER       NOT NULL,
    APPLICATION_ID    NUMBER,
    USER_ID           NUMBER       NOT NULL,
    COURSE_ID         NUMBER       NOT NULL,
    PROGRESS_RATE     NUMBER       DEFAULT 0 NOT NULL,
    LAST_PLAY_SECONDS NUMBER       DEFAULT 0 NOT NULL,
    LEARNING_STATUS   VARCHAR2(30) DEFAULT 'NOT_STARTED' NOT NULL,
    COMPLETION_STATUS VARCHAR2(30) DEFAULT 'INCOMPLETE' NOT NULL,
    STARTED_AT        DATE,
    COMPLETED_AT      DATE,
    CONSTRAINT PK_COURSE_LEARNING PRIMARY KEY (LEARNING_ID),
    CONSTRAINT UK_LEARNING_USER_COURSE UNIQUE (USER_ID, COURSE_ID),
    CONSTRAINT UK_LEARNING_APP UNIQUE (APPLICATION_ID),
    CONSTRAINT CK_LEARNING_PROGRESS CHECK (PROGRESS_RATE BETWEEN 0 AND 100),
    CONSTRAINT CK_LAST_PLAY_SECONDS CHECK (LAST_PLAY_SECONDS >= 0)
);

CREATE TABLE LEARNING_LOG (
    LOG_ID        NUMBER        NOT NULL,
    LEARNING_ID   NUMBER        NOT NULL,
    USER_ID       NUMBER        NOT NULL,
    COURSE_ID     NUMBER        NOT NULL,
    CHAPTER_ID    NUMBER,
    EVENT_TYPE    VARCHAR2(50)  NOT NULL,
    PLAY_SECONDS  NUMBER        DEFAULT 0 NOT NULL,
    PROGRESS_RATE NUMBER        DEFAULT 0 NOT NULL,
    EVENT_AT      DATE          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_LEARNING_LOG PRIMARY KEY (LOG_ID),
    CONSTRAINT CK_LOG_PLAY_SECONDS CHECK (PLAY_SECONDS >= 0),
    CONSTRAINT CK_LOG_PROGRESS CHECK (PROGRESS_RATE BETWEEN 0 AND 100)
);

CREATE TABLE QUIZ (
    QUIZ_ID         NUMBER        NOT NULL,
    COURSE_ID       NUMBER        NOT NULL,
    CHAPTER_ID      NUMBER,
    QUESTION_TYPE   VARCHAR2(30)  NOT NULL,
    QUESTION_TEXT   CLOB          NOT NULL,
    EXPLANATION     CLOB,
    DIFFICULTY      VARCHAR2(30),
    ANSWER_TEXT     VARCHAR2(4000),
    STATUS          VARCHAR2(30)  DEFAULT 'DRAFT' NOT NULL,
    AI_GENERATED_YN VARCHAR2(1)   DEFAULT 'N' NOT NULL,
    CREATED_AT      DATE          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_QUIZ PRIMARY KEY (QUIZ_ID),
    CONSTRAINT CK_QUIZ_AI_YN CHECK (AI_GENERATED_YN IN ('Y', 'N'))
);

CREATE TABLE QUIZ_OPTION (
    OPTION_ID  NUMBER       NOT NULL,
    QUIZ_ID    NUMBER       NOT NULL,
    OPTION_NO  VARCHAR2(10) NOT NULL,
    OPTION_TEXT CLOB        NOT NULL,
    CORRECT_YN VARCHAR2(1)  DEFAULT 'N' NOT NULL,
    CONSTRAINT PK_QUIZ_OPTION PRIMARY KEY (OPTION_ID),
    CONSTRAINT UK_QUIZ_OPTION_NO UNIQUE (QUIZ_ID, OPTION_NO),
    CONSTRAINT CK_QUIZ_OPTION_CORRECT CHECK (CORRECT_YN IN ('Y', 'N'))
);

CREATE TABLE QUIZ_ATTEMPT (
    ATTEMPT_ID   NUMBER       NOT NULL,
    USER_ID      NUMBER       NOT NULL,
    COURSE_ID    NUMBER       NOT NULL,
    CHAPTER_ID   NUMBER,
    ATTEMPT_NO   NUMBER       DEFAULT 1 NOT NULL,
    SCORE        NUMBER       DEFAULT 0 NOT NULL,
    PASS_YN      VARCHAR2(1)  DEFAULT 'N' NOT NULL,
    SUBMITTED_AT DATE         DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_QUIZ_ATTEMPT PRIMARY KEY (ATTEMPT_ID),
    CONSTRAINT UK_QUIZ_ATTEMPT_NO UNIQUE (USER_ID, COURSE_ID, CHAPTER_ID, ATTEMPT_NO),
    CONSTRAINT CK_QUIZ_ATTEMPT_PASS CHECK (PASS_YN IN ('Y', 'N')),
    CONSTRAINT CK_QUIZ_ATTEMPT_SCORE CHECK (SCORE >= 0)
);

CREATE TABLE QUIZ_ATTEMPT_ANSWER (
    ATTEMPT_ANSWER_ID NUMBER       NOT NULL,
    ATTEMPT_ID        NUMBER       NOT NULL,
    QUIZ_ID           NUMBER       NOT NULL,
    SELECTED_OPTION_ID NUMBER,
    ANSWER_TEXT       CLOB,
    CORRECT_YN        VARCHAR2(1)  DEFAULT 'N' NOT NULL,
    CONSTRAINT PK_QUIZ_ATTEMPT_ANSWER PRIMARY KEY (ATTEMPT_ANSWER_ID),
    CONSTRAINT UK_ATTEMPT_QUIZ UNIQUE (ATTEMPT_ID, QUIZ_ID),
    CONSTRAINT CK_ATTEMPT_ANSWER_CORRECT CHECK (CORRECT_YN IN ('Y', 'N'))
);

CREATE TABLE COMPETENCY (
    COMPETENCY_ID   NUMBER        NOT NULL,
    COMPETENCY_NAME VARCHAR2(100) NOT NULL,
    DESCRIPTION     VARCHAR2(1000),
    STANDARD_SCORE  NUMBER,
    USE_YN          VARCHAR2(1)   DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_COMPETENCY PRIMARY KEY (COMPETENCY_ID),
    CONSTRAINT CK_COMPETENCY_USE_YN CHECK (USE_YN IN ('Y', 'N'))
);

CREATE TABLE COURSE_COMPETENCY_WEIGHT (
    WEIGHT_ID     NUMBER NOT NULL,
    COURSE_ID     NUMBER NOT NULL,
    COMPETENCY_ID NUMBER NOT NULL,
    WEIGHT        NUMBER DEFAULT 1 NOT NULL,
    CONSTRAINT PK_COURSE_COMP_WEIGHT PRIMARY KEY (WEIGHT_ID),
    CONSTRAINT UK_COURSE_COMP_WEIGHT UNIQUE (COURSE_ID, COMPETENCY_ID),
    CONSTRAINT CK_COURSE_COMP_WEIGHT CHECK (WEIGHT >= 0)
);

CREATE TABLE USER_COMPETENCY_SCORE (
    USER_SCORE_ID NUMBER NOT NULL,
    USER_ID       NUMBER NOT NULL,
    COMPETENCY_ID NUMBER NOT NULL,
    SCORE         NUMBER DEFAULT 0 NOT NULL,
    CALCULATED_AT DATE   DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_USER_COMP_SCORE PRIMARY KEY (USER_SCORE_ID),
    CONSTRAINT UK_USER_COMP_SCORE UNIQUE (USER_ID, COMPETENCY_ID),
    CONSTRAINT CK_USER_COMP_SCORE CHECK (SCORE >= 0)
);

CREATE TABLE COMPETENCY_SCORE_HISTORY (
    HISTORY_ID    NUMBER         NOT NULL,
    USER_ID       NUMBER         NOT NULL,
    COMPETENCY_ID NUMBER         NOT NULL,
    SCORE         NUMBER         DEFAULT 0 NOT NULL,
    CALC_REASON   VARCHAR2(1000),
    CALCULATED_AT DATE           DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_COMP_SCORE_HISTORY PRIMARY KEY (HISTORY_ID),
    CONSTRAINT CK_COMP_SCORE_HIST_SCORE CHECK (SCORE >= 0)
);

CREATE TABLE CAREER_DIAGNOSIS (
    DIAGNOSIS_ID NUMBER NOT NULL,
    USER_ID      NUMBER NOT NULL,
    LLM_SUMMARY  CLOB,
    CREATED_AT   DATE   DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_CAREER_DIAGNOSIS PRIMARY KEY (DIAGNOSIS_ID)
);

CREATE TABLE CAREER_TARGET_SKILL (
    TARGET_SKILL_ID NUMBER NOT NULL,
    DIAGNOSIS_ID    NUMBER NOT NULL,
    SKILL_ID        NUMBER NOT NULL,
    CONSTRAINT PK_CAREER_TARGET_SKILL PRIMARY KEY (TARGET_SKILL_ID),
    CONSTRAINT UK_CAREER_TARGET_SKILL UNIQUE (DIAGNOSIS_ID, SKILL_ID)
);

CREATE TABLE LEVEL_TEST_QUESTION (
    LEVEL_QUESTION_ID NUMBER       NOT NULL,
    DIAGNOSIS_ID      NUMBER       NOT NULL,
    SKILL_ID          NUMBER       NOT NULL,
    QUESTION_TEXT     CLOB         NOT NULL,
    QUESTION_TYPE     VARCHAR2(30) NOT NULL,
    DIFFICULTY        VARCHAR2(30),
    EXPLANATION       CLOB,
    CONSTRAINT PK_LEVEL_TEST_QUESTION PRIMARY KEY (LEVEL_QUESTION_ID)
);

CREATE TABLE LEVEL_TEST_OPTION (
    LEVEL_OPTION_ID    NUMBER       NOT NULL,
    LEVEL_QUESTION_ID  NUMBER       NOT NULL,
    OPTION_NO          VARCHAR2(10) NOT NULL,
    OPTION_TEXT        CLOB         NOT NULL,
    CORRECT_YN         VARCHAR2(1)  DEFAULT 'N' NOT NULL,
    CONSTRAINT PK_LEVEL_TEST_OPTION PRIMARY KEY (LEVEL_OPTION_ID),
    CONSTRAINT UK_LEVEL_TEST_OPTION UNIQUE (LEVEL_QUESTION_ID, OPTION_NO),
    CONSTRAINT CK_LEVEL_OPTION_CORRECT CHECK (CORRECT_YN IN ('Y', 'N'))
);

CREATE TABLE LEVEL_TEST_ANSWER_LOG (
    LEVEL_ANSWER_ID   NUMBER      NOT NULL,
    USER_ID           NUMBER      NOT NULL,
    LEVEL_QUESTION_ID NUMBER      NOT NULL,
    SELECTED_OPTION_ID NUMBER,
    CORRECT_YN        VARCHAR2(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT PK_LEVEL_TEST_ANSWER_LOG PRIMARY KEY (LEVEL_ANSWER_ID),
    CONSTRAINT UK_LEVEL_ANSWER UNIQUE (USER_ID, LEVEL_QUESTION_ID),
    CONSTRAINT CK_LEVEL_ANSWER_CORRECT CHECK (CORRECT_YN IN ('Y', 'N'))
);

CREATE TABLE CAREER_RECOMMENDATION (
    RECOMMENDATION_ID NUMBER NOT NULL,
    DIAGNOSIS_ID      NUMBER NOT NULL,
    COURSE_ID         NUMBER NOT NULL,
    RECOMMEND_RANK    NUMBER,
    MATCH_SCORE       NUMBER,
    RECOMMEND_REASON  CLOB,
    CREATED_AT        DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_CAREER_RECOMMENDATION PRIMARY KEY (RECOMMENDATION_ID),
    CONSTRAINT UK_CAREER_RECOMMEND UNIQUE (DIAGNOSIS_ID, COURSE_ID)
);

CREATE TABLE KCY_QUESTION (
    KCY_QUESTION_ID NUMBER       NOT NULL,
    QUESTION_TEXT   CLOB         NOT NULL,
    SORT_ORDER      NUMBER,
    USE_YN          VARCHAR2(1)  DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_KCY_QUESTION PRIMARY KEY (KCY_QUESTION_ID),
    CONSTRAINT CK_KCY_QUESTION_USE_YN CHECK (USE_YN IN ('Y', 'N'))
);

CREATE TABLE KCY_OPTION (
    KCY_OPTION_ID     NUMBER       NOT NULL,
    KCY_QUESTION_ID   NUMBER       NOT NULL,
    OPTION_NO         VARCHAR2(10) NOT NULL,
    OPTION_TEXT       CLOB         NOT NULL,
    ACTION_SCORE      NUMBER       DEFAULT 0 NOT NULL,
    OUTLINE_SCORE     NUMBER       DEFAULT 0 NOT NULL,
    WIDE_SCORE        NUMBER       DEFAULT 0 NOT NULL,
    DEEP_SCORE        NUMBER       DEFAULT 0 NOT NULL,
    INDEPENDENT_SCORE NUMBER       DEFAULT 0 NOT NULL,
    CORPORATE_SCORE   NUMBER       DEFAULT 0 NOT NULL,
    PROMPTER_SCORE    NUMBER       DEFAULT 0 NOT NULL,
    MANUAL_SCORE      NUMBER       DEFAULT 0 NOT NULL,
    CONSTRAINT PK_KCY_OPTION PRIMARY KEY (KCY_OPTION_ID),
    CONSTRAINT UK_KCY_OPTION_NO UNIQUE (KCY_QUESTION_ID, OPTION_NO)
);

/* =========================
   3. FOREIGN KEYS
   ========================= */
ALTER TABLE DEPARTMENT ADD CONSTRAINT FK_DEPT_PARENT
    FOREIGN KEY (PARENT_DEPARTMENT_ID) REFERENCES DEPARTMENT (DEPARTMENT_ID);

ALTER TABLE SKILL ADD CONSTRAINT FK_SKILL_PARENT
    FOREIGN KEY (PARENT_SKILL_ID) REFERENCES SKILL (SKILL_ID);

ALTER TABLE USERS ADD CONSTRAINT FK_USERS_DEPT
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT (DEPARTMENT_ID);
ALTER TABLE USERS ADD CONSTRAINT FK_USERS_JOB
    FOREIGN KEY (JOB_ID) REFERENCES JOB (JOB_ID);
ALTER TABLE USERS ADD CONSTRAINT FK_USERS_POSITION
    FOREIGN KEY (POSITION_ID) REFERENCES POSITION (POSITION_ID);

ALTER TABLE DEPARTMENT_SKILL ADD CONSTRAINT FK_DEPT_SKILL_DEPT
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT (DEPARTMENT_ID);
ALTER TABLE DEPARTMENT_SKILL ADD CONSTRAINT FK_DEPT_SKILL_SKILL
    FOREIGN KEY (SKILL_ID) REFERENCES SKILL (SKILL_ID);

ALTER TABLE USER_ROLE ADD CONSTRAINT FK_USER_ROLE_USER
    FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID);
ALTER TABLE USER_ROLE ADD CONSTRAINT FK_USER_ROLE_ROLE
    FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ROLE_ID);

ALTER TABLE USER_INTEREST ADD CONSTRAINT FK_USER_INTEREST_USER
    FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID);
ALTER TABLE USER_INTEREST ADD CONSTRAINT FK_USER_INTEREST_SKILL
    FOREIGN KEY (SKILL_ID) REFERENCES SKILL (SKILL_ID);

ALTER TABLE COURSE ADD CONSTRAINT FK_COURSE_CREATED_BY
    FOREIGN KEY (CREATED_BY) REFERENCES USERS (USER_ID);

ALTER TABLE ONLINE_COURSE ADD CONSTRAINT FK_ONLINE_COURSE
    FOREIGN KEY (COURSE_ID) REFERENCES COURSE (COURSE_ID);
ALTER TABLE OFFLINE_COURSE ADD CONSTRAINT FK_OFFLINE_COURSE
    FOREIGN KEY (COURSE_ID) REFERENCES COURSE (COURSE_ID);

ALTER TABLE COURSE_PREREQUISITE ADD CONSTRAINT FK_COURSE_PREREQ_COURSE
    FOREIGN KEY (COURSE_ID) REFERENCES COURSE (COURSE_ID);
ALTER TABLE COURSE_PREREQUISITE ADD CONSTRAINT FK_COURSE_PREREQ_TARGET
    FOREIGN KEY (PREREQUISITE_COURSE_ID) REFERENCES COURSE (COURSE_ID);

ALTER TABLE COURSE_CHAPTER ADD CONSTRAINT FK_COURSE_CHAPTER_COURSE
    FOREIGN KEY (COURSE_ID) REFERENCES COURSE (COURSE_ID);

ALTER TABLE COURSE_SKILL ADD CONSTRAINT FK_COURSE_SKILL_COURSE
    FOREIGN KEY (COURSE_ID) REFERENCES COURSE (COURSE_ID);
ALTER TABLE COURSE_SKILL ADD CONSTRAINT FK_COURSE_SKILL_SKILL
    FOREIGN KEY (SKILL_ID) REFERENCES SKILL (SKILL_ID);

ALTER TABLE CHAPTER_SKILL ADD CONSTRAINT FK_CHAPTER_SKILL_CHAPTER
    FOREIGN KEY (CHAPTER_ID) REFERENCES COURSE_CHAPTER (CHAPTER_ID);
ALTER TABLE CHAPTER_SKILL ADD CONSTRAINT FK_CHAPTER_SKILL_SKILL
    FOREIGN KEY (SKILL_ID) REFERENCES SKILL (SKILL_ID);

ALTER TABLE COURSE_APPLICATION ADD CONSTRAINT FK_APP_USER
    FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID);
ALTER TABLE COURSE_APPLICATION ADD CONSTRAINT FK_APP_COURSE
    FOREIGN KEY (COURSE_ID) REFERENCES COURSE (COURSE_ID);
ALTER TABLE COURSE_APPLICATION ADD CONSTRAINT FK_APP_APPROVER
    FOREIGN KEY (APPROVED_BY) REFERENCES USERS (USER_ID);

ALTER TABLE COURSE_LEARNING_STATUS ADD CONSTRAINT FK_LEARNING_APP
    FOREIGN KEY (APPLICATION_ID) REFERENCES COURSE_APPLICATION (APPLICATION_ID);
ALTER TABLE COURSE_LEARNING_STATUS ADD CONSTRAINT FK_LEARNING_USER
    FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID);
ALTER TABLE COURSE_LEARNING_STATUS ADD CONSTRAINT FK_LEARNING_COURSE
    FOREIGN KEY (COURSE_ID) REFERENCES COURSE (COURSE_ID);

ALTER TABLE LEARNING_LOG ADD CONSTRAINT FK_LOG_LEARNING
    FOREIGN KEY (LEARNING_ID) REFERENCES COURSE_LEARNING_STATUS (LEARNING_ID);
ALTER TABLE LEARNING_LOG ADD CONSTRAINT FK_LOG_USER
    FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID);
ALTER TABLE LEARNING_LOG ADD CONSTRAINT FK_LOG_COURSE
    FOREIGN KEY (COURSE_ID) REFERENCES COURSE (COURSE_ID);
ALTER TABLE LEARNING_LOG ADD CONSTRAINT FK_LOG_CHAPTER
    FOREIGN KEY (CHAPTER_ID) REFERENCES COURSE_CHAPTER (CHAPTER_ID);

ALTER TABLE QUIZ ADD CONSTRAINT FK_QUIZ_COURSE
    FOREIGN KEY (COURSE_ID) REFERENCES COURSE (COURSE_ID);
ALTER TABLE QUIZ ADD CONSTRAINT FK_QUIZ_CHAPTER
    FOREIGN KEY (CHAPTER_ID) REFERENCES COURSE_CHAPTER (CHAPTER_ID);

ALTER TABLE QUIZ_OPTION ADD CONSTRAINT FK_QUIZ_OPTION_QUIZ
    FOREIGN KEY (QUIZ_ID) REFERENCES QUIZ (QUIZ_ID);

ALTER TABLE QUIZ_ATTEMPT ADD CONSTRAINT FK_ATTEMPT_USER
    FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID);
ALTER TABLE QUIZ_ATTEMPT ADD CONSTRAINT FK_ATTEMPT_COURSE
    FOREIGN KEY (COURSE_ID) REFERENCES COURSE (COURSE_ID);
ALTER TABLE QUIZ_ATTEMPT ADD CONSTRAINT FK_ATTEMPT_CHAPTER
    FOREIGN KEY (CHAPTER_ID) REFERENCES COURSE_CHAPTER (CHAPTER_ID);

ALTER TABLE QUIZ_ATTEMPT_ANSWER ADD CONSTRAINT FK_ATT_ANSWER_ATTEMPT
    FOREIGN KEY (ATTEMPT_ID) REFERENCES QUIZ_ATTEMPT (ATTEMPT_ID);
ALTER TABLE QUIZ_ATTEMPT_ANSWER ADD CONSTRAINT FK_ATT_ANSWER_QUIZ
    FOREIGN KEY (QUIZ_ID) REFERENCES QUIZ (QUIZ_ID);
ALTER TABLE QUIZ_ATTEMPT_ANSWER ADD CONSTRAINT FK_ATT_ANSWER_OPTION
    FOREIGN KEY (SELECTED_OPTION_ID) REFERENCES QUIZ_OPTION (OPTION_ID);

ALTER TABLE COURSE_COMPETENCY_WEIGHT ADD CONSTRAINT FK_COURSE_COMP_COURSE
    FOREIGN KEY (COURSE_ID) REFERENCES COURSE (COURSE_ID);
ALTER TABLE COURSE_COMPETENCY_WEIGHT ADD CONSTRAINT FK_COURSE_COMP_COMP
    FOREIGN KEY (COMPETENCY_ID) REFERENCES COMPETENCY (COMPETENCY_ID);

ALTER TABLE USER_COMPETENCY_SCORE ADD CONSTRAINT FK_USER_COMP_USER
    FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID);
ALTER TABLE USER_COMPETENCY_SCORE ADD CONSTRAINT FK_USER_COMP_COMP
    FOREIGN KEY (COMPETENCY_ID) REFERENCES COMPETENCY (COMPETENCY_ID);

ALTER TABLE COMPETENCY_SCORE_HISTORY ADD CONSTRAINT FK_COMP_HIST_USER
    FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID);
ALTER TABLE COMPETENCY_SCORE_HISTORY ADD CONSTRAINT FK_COMP_HIST_COMP
    FOREIGN KEY (COMPETENCY_ID) REFERENCES COMPETENCY (COMPETENCY_ID);

ALTER TABLE CAREER_DIAGNOSIS ADD CONSTRAINT FK_DIAGNOSIS_USER
    FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID);

ALTER TABLE CAREER_TARGET_SKILL ADD CONSTRAINT FK_TARGET_SKILL_DIAG
    FOREIGN KEY (DIAGNOSIS_ID) REFERENCES CAREER_DIAGNOSIS (DIAGNOSIS_ID);
ALTER TABLE CAREER_TARGET_SKILL ADD CONSTRAINT FK_TARGET_SKILL_SKILL
    FOREIGN KEY (SKILL_ID) REFERENCES SKILL (SKILL_ID);

ALTER TABLE LEVEL_TEST_QUESTION ADD CONSTRAINT FK_LEVEL_QUESTION_DIAG
    FOREIGN KEY (DIAGNOSIS_ID) REFERENCES CAREER_DIAGNOSIS (DIAGNOSIS_ID);
ALTER TABLE LEVEL_TEST_QUESTION ADD CONSTRAINT FK_LEVEL_QUESTION_SKILL
    FOREIGN KEY (SKILL_ID) REFERENCES SKILL (SKILL_ID);

ALTER TABLE LEVEL_TEST_OPTION ADD CONSTRAINT FK_LEVEL_OPTION_QUESTION
    FOREIGN KEY (LEVEL_QUESTION_ID) REFERENCES LEVEL_TEST_QUESTION (LEVEL_QUESTION_ID);

ALTER TABLE LEVEL_TEST_ANSWER_LOG ADD CONSTRAINT FK_LEVEL_ANSWER_USER
    FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID);
ALTER TABLE LEVEL_TEST_ANSWER_LOG ADD CONSTRAINT FK_LEVEL_ANSWER_QUESTION
    FOREIGN KEY (LEVEL_QUESTION_ID) REFERENCES LEVEL_TEST_QUESTION (LEVEL_QUESTION_ID);
ALTER TABLE LEVEL_TEST_ANSWER_LOG ADD CONSTRAINT FK_LEVEL_ANSWER_OPTION
    FOREIGN KEY (SELECTED_OPTION_ID) REFERENCES LEVEL_TEST_OPTION (LEVEL_OPTION_ID);

ALTER TABLE CAREER_RECOMMENDATION ADD CONSTRAINT FK_CAREER_REC_DIAG
    FOREIGN KEY (DIAGNOSIS_ID) REFERENCES CAREER_DIAGNOSIS (DIAGNOSIS_ID);
ALTER TABLE CAREER_RECOMMENDATION ADD CONSTRAINT FK_CAREER_REC_COURSE
    FOREIGN KEY (COURSE_ID) REFERENCES COURSE (COURSE_ID);

ALTER TABLE KCY_OPTION ADD CONSTRAINT FK_KCY_OPTION_QUESTION
    FOREIGN KEY (KCY_QUESTION_ID) REFERENCES KCY_QUESTION (KCY_QUESTION_ID);

/* =========================
   4. FK INDEXES
   Oracle은 FK 인덱스를 자동 생성하지 않으므로 조회/조인용 인덱스를 별도로 둔다.
   ========================= */
CREATE INDEX IX_DEPT_PARENT ON DEPARTMENT (PARENT_DEPARTMENT_ID);
CREATE INDEX IX_SKILL_PARENT ON SKILL (PARENT_SKILL_ID);
CREATE INDEX IX_USERS_DEPT ON USERS (DEPARTMENT_ID);
CREATE INDEX IX_USERS_JOB ON USERS (JOB_ID);
CREATE INDEX IX_USERS_POSITION ON USERS (POSITION_ID);
CREATE INDEX IX_DEPT_SKILL_DEPT ON DEPARTMENT_SKILL (DEPARTMENT_ID);
CREATE INDEX IX_DEPT_SKILL_SKILL ON DEPARTMENT_SKILL (SKILL_ID);
CREATE INDEX IX_USER_ROLE_USER ON USER_ROLE (USER_ID);
CREATE INDEX IX_USER_ROLE_ROLE ON USER_ROLE (ROLE_ID);
CREATE INDEX IX_USER_INTEREST_USER ON USER_INTEREST (USER_ID);
CREATE INDEX IX_USER_INTEREST_SKILL ON USER_INTEREST (SKILL_ID);
CREATE INDEX IX_COURSE_CREATED_BY ON COURSE (CREATED_BY);
CREATE INDEX IX_CHAPTER_COURSE ON COURSE_CHAPTER (COURSE_ID);
CREATE INDEX IX_COURSE_SKILL_COURSE ON COURSE_SKILL (COURSE_ID);
CREATE INDEX IX_COURSE_SKILL_SKILL ON COURSE_SKILL (SKILL_ID);
CREATE INDEX IX_CHAPTER_SKILL_CHAPTER ON CHAPTER_SKILL (CHAPTER_ID);
CREATE INDEX IX_CHAPTER_SKILL_SKILL ON CHAPTER_SKILL (SKILL_ID);
CREATE INDEX IX_APP_USER ON COURSE_APPLICATION (USER_ID);
CREATE INDEX IX_APP_COURSE ON COURSE_APPLICATION (COURSE_ID);
CREATE INDEX IX_APP_APPROVER ON COURSE_APPLICATION (APPROVED_BY);
CREATE INDEX IX_LEARNING_USER ON COURSE_LEARNING_STATUS (USER_ID);
CREATE INDEX IX_LEARNING_COURSE ON COURSE_LEARNING_STATUS (COURSE_ID);
CREATE INDEX IX_LOG_LEARNING ON LEARNING_LOG (LEARNING_ID);
CREATE INDEX IX_LOG_USER ON LEARNING_LOG (USER_ID);
CREATE INDEX IX_LOG_COURSE ON LEARNING_LOG (COURSE_ID);
CREATE INDEX IX_LOG_CHAPTER ON LEARNING_LOG (CHAPTER_ID);
CREATE INDEX IX_LOG_EVENT_AT ON LEARNING_LOG (EVENT_AT);
CREATE INDEX IX_QUIZ_COURSE ON QUIZ (COURSE_ID);
CREATE INDEX IX_QUIZ_CHAPTER ON QUIZ (CHAPTER_ID);
CREATE INDEX IX_QUIZ_OPTION_QUIZ ON QUIZ_OPTION (QUIZ_ID);
CREATE INDEX IX_ATTEMPT_USER_COURSE ON QUIZ_ATTEMPT (USER_ID, COURSE_ID);
CREATE INDEX IX_ATT_ANSWER_ATTEMPT ON QUIZ_ATTEMPT_ANSWER (ATTEMPT_ID);
CREATE INDEX IX_USER_COMP_USER ON USER_COMPETENCY_SCORE (USER_ID);
CREATE INDEX IX_COMP_HIST_USER ON COMPETENCY_SCORE_HISTORY (USER_ID);
CREATE INDEX IX_DIAGNOSIS_USER ON CAREER_DIAGNOSIS (USER_ID);
CREATE INDEX IX_LEVEL_QUESTION_DIAG ON LEVEL_TEST_QUESTION (DIAGNOSIS_ID);
CREATE INDEX IX_CAREER_REC_DIAG ON CAREER_RECOMMENDATION (DIAGNOSIS_ID);
CREATE INDEX IX_KCY_OPTION_QUESTION ON KCY_OPTION (KCY_QUESTION_ID);

/* =========================
   5. BASIC ROLE SEED DATA
   필요 없으면 삭제 가능
   ========================= */
INSERT INTO ROLES (ROLE_ID, ROLE_CODE, ROLE_NAME) VALUES (ROLES_SEQ.NEXTVAL, 'ROLE_USER', '임직원');
INSERT INTO ROLES (ROLE_ID, ROLE_CODE, ROLE_NAME) VALUES (ROLES_SEQ.NEXTVAL, 'ROLE_HR', 'HR 관리자');
INSERT INTO ROLES (ROLE_ID, ROLE_CODE, ROLE_NAME) VALUES (ROLES_SEQ.NEXTVAL, 'ROLE_LEADER', '팀장');

COMMIT;
