/* =========================================================
   V2__alter_schema.sql
   H-Link Oracle Migration

   반영 내용
   1) COURSE_APPLICATION을 신청 이력 로그성 테이블로 변경
      - UK(USER_ID, COURSE_ID) 제거
      - APPLICATION_TYPE, CANCELED_AT 추가
   2) COURSE_LEARNING_STATUS를 강의 전체 학습 상태 테이블로 정리
      - LEARNING_ID -> COURSE_LEARNING_ID
      - LAST_PLAY_SECONDS 제거
      - LEARNING_STATUS, COMPLETION_STATUS -> STATUS 통합
      - UPDATED_AT 추가
   3) CHAPTER_LEARNING_STATUS 신규 추가
      - 챕터별 진도율, 재생 위치, 퀴즈 응시 연결 관리
   4) LEARNING_LOG가 COURSE_LEARNING_STATUS와 CHAPTER_LEARNING_STATUS를 모두 참조하도록 변경
   5) QUIZ는 챕터별 퀴즈 정책 반영
      - CHAPTER_ID NOT NULL 권장/적용
      - UPDATED_AT 추가
   6) QUIZ_ATTEMPT는 실제 제출 이력만 저장하도록 단순화
      - ATTEMPT_NO, SCORE, PASS_YN 제거
      - UNIQUE(USER_ID, COURSE_ID, CHAPTER_ID) 적용
   7) OFFLINE_COURSE에 CURRENT_APPLICANT_COUNT 추가
      - APPROVED 상태 신청 건 수를 캐싱하는 컬럼
   8) ONLINE_COURSE / OFFLINE_COURSE 상태값을 OPEN, CANCELED, HIDDEN 기준으로 정리

   주의
   - 기존 데이터에 QUIZ.CHAPTER_ID가 NULL인 row가 있으면 NOT NULL 변경에서 실패한다.
   - 기존 데이터에 USER_ID, COURSE_ID, CHAPTER_ID 기준 중복 QUIZ_ATTEMPT가 있으면 UK 생성에서 실패한다.
   - 기존 데이터가 있는 경우 실행 전 데이터 정리가 필요하다.
   ========================================================= */

/* =========================================================
   1. COURSE_APPLICATION 변경
   ========================================================= */

ALTER TABLE COURSE_APPLICATION DROP CONSTRAINT UK_COURSE_APPLICATION;

ALTER TABLE COURSE_APPLICATION ADD (
    APPLICATION_TYPE VARCHAR2(30) DEFAULT 'USER' NOT NULL,
    CANCELED_AT      DATE
);

ALTER TABLE COURSE_APPLICATION ADD CONSTRAINT CK_APP_TYPE
CHECK (APPLICATION_TYPE IN ('USER', 'ADMIN_ASSIGN'));

/* =========================================================
   2. COURSE_LEARNING_STATUS 변경 준비
      - LEARNING_LOG가 기존 LEARNING_ID FK를 참조하므로 먼저 FK/인덱스 제거
   ========================================================= */

ALTER TABLE LEARNING_LOG DROP CONSTRAINT FK_LOG_LEARNING;
DROP INDEX IX_LOG_LEARNING;

/* 컬럼명 변경: LEARNING_ID -> COURSE_LEARNING_ID */
ALTER TABLE COURSE_LEARNING_STATUS RENAME COLUMN LEARNING_ID TO COURSE_LEARNING_ID;
ALTER TABLE LEARNING_LOG RENAME COLUMN LEARNING_ID TO COURSE_LEARNING_ID;

/* STATUS 컬럼 추가 후 기존 상태값을 최대한 보존 */
ALTER TABLE COURSE_LEARNING_STATUS ADD (
    STATUS     VARCHAR2(30) DEFAULT 'NOT_STARTED',
    UPDATED_AT DATE
);

UPDATE COURSE_LEARNING_STATUS
SET STATUS = CASE
    WHEN COMPLETION_STATUS = 'COMPLETED' THEN 'COMPLETED'
    WHEN LEARNING_STATUS = 'IN_PROGRESS' THEN 'IN_PROGRESS'
    WHEN LEARNING_STATUS = 'COMPLETED' THEN 'COMPLETED'
    ELSE 'NOT_STARTED'
END;

ALTER TABLE COURSE_LEARNING_STATUS MODIFY STATUS NOT NULL;

/* 기존 컬럼 제거 */
ALTER TABLE COURSE_LEARNING_STATUS DROP CONSTRAINT CK_LAST_PLAY_SECONDS;
ALTER TABLE COURSE_LEARNING_STATUS DROP COLUMN LAST_PLAY_SECONDS;
ALTER TABLE COURSE_LEARNING_STATUS DROP COLUMN LEARNING_STATUS;
ALTER TABLE COURSE_LEARNING_STATUS DROP COLUMN COMPLETION_STATUS;

ALTER TABLE COURSE_LEARNING_STATUS ADD CONSTRAINT CK_COURSE_LEARNING_STATUS
CHECK (STATUS IN ('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'CANCELED'));

/* =========================================================
   3. CHAPTER_LEARNING_STATUS 추가
   ========================================================= */

CREATE SEQUENCE CHAPTER_LEARNING_STATUS_SEQ
START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE CHAPTER_LEARNING_STATUS (
    CHAPTER_LEARNING_ID NUMBER       NOT NULL,
    COURSE_LEARNING_ID  NUMBER       NOT NULL,
    USER_ID             NUMBER       NOT NULL,
    COURSE_ID           NUMBER       NOT NULL,
    CHAPTER_ID          NUMBER       NOT NULL,
    PROGRESS_RATE       NUMBER       DEFAULT 0 NOT NULL,
    LAST_PLAY_SECONDS   NUMBER       DEFAULT 0 NOT NULL,
    MAX_PLAY_SECONDS    NUMBER       DEFAULT 0 NOT NULL,
    QUIZ_ATTEMPT_ID     NUMBER,
    STATUS              VARCHAR2(30) DEFAULT 'NOT_STARTED' NOT NULL,
    STARTED_AT          DATE,
    COMPLETED_AT        DATE,
    UPDATED_AT          DATE,
    CONSTRAINT PK_CHAPTER_LEARNING_STATUS PRIMARY KEY (CHAPTER_LEARNING_ID),
    CONSTRAINT UK_CHAPTER_LEARNING_STATUS UNIQUE (COURSE_LEARNING_ID, CHAPTER_ID),
    CONSTRAINT CK_CHAPTER_LEARNING_PROGRESS CHECK (PROGRESS_RATE BETWEEN 0 AND 100),
    CONSTRAINT CK_CHAPTER_LAST_PLAY_SECONDS CHECK (LAST_PLAY_SECONDS >= 0),
    CONSTRAINT CK_CHAPTER_MAX_PLAY_SECONDS CHECK (MAX_PLAY_SECONDS >= 0),
    CONSTRAINT CK_CHAPTER_LEARNING_STATUS CHECK (STATUS IN ('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED'))
);

ALTER TABLE CHAPTER_LEARNING_STATUS ADD CONSTRAINT FK_CHAPTER_LEARNING_COURSE_LEARNING
FOREIGN KEY (COURSE_LEARNING_ID) REFERENCES COURSE_LEARNING_STATUS (COURSE_LEARNING_ID);

ALTER TABLE CHAPTER_LEARNING_STATUS ADD CONSTRAINT FK_CHAPTER_LEARNING_USER
FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID);

ALTER TABLE CHAPTER_LEARNING_STATUS ADD CONSTRAINT FK_CHAPTER_LEARNING_COURSE
FOREIGN KEY (COURSE_ID) REFERENCES COURSE (COURSE_ID);

ALTER TABLE CHAPTER_LEARNING_STATUS ADD CONSTRAINT FK_CHAPTER_LEARNING_CHAPTER
FOREIGN KEY (CHAPTER_ID) REFERENCES COURSE_CHAPTER (CHAPTER_ID);

CREATE INDEX IX_CHAPTER_LEARNING_COURSE_LEARNING ON CHAPTER_LEARNING_STATUS (COURSE_LEARNING_ID);
CREATE INDEX IX_CHAPTER_LEARNING_USER ON CHAPTER_LEARNING_STATUS (USER_ID);
CREATE INDEX IX_CHAPTER_LEARNING_COURSE ON CHAPTER_LEARNING_STATUS (COURSE_ID);
CREATE INDEX IX_CHAPTER_LEARNING_CHAPTER ON CHAPTER_LEARNING_STATUS (CHAPTER_ID);
CREATE INDEX IX_CHAPTER_LEARNING_ATTEMPT ON CHAPTER_LEARNING_STATUS (QUIZ_ATTEMPT_ID);

/* =========================================================
   4. LEARNING_LOG 변경
   ========================================================= */

ALTER TABLE LEARNING_LOG ADD (
    CHAPTER_LEARNING_ID NUMBER
);

ALTER TABLE LEARNING_LOG ADD CONSTRAINT FK_LOG_COURSE_LEARNING
FOREIGN KEY (COURSE_LEARNING_ID) REFERENCES COURSE_LEARNING_STATUS (COURSE_LEARNING_ID);

ALTER TABLE LEARNING_LOG ADD CONSTRAINT FK_LOG_CHAPTER_LEARNING
FOREIGN KEY (CHAPTER_LEARNING_ID) REFERENCES CHAPTER_LEARNING_STATUS (CHAPTER_LEARNING_ID);

CREATE INDEX IX_LOG_COURSE_LEARNING ON LEARNING_LOG (COURSE_LEARNING_ID);
CREATE INDEX IX_LOG_CHAPTER_LEARNING ON LEARNING_LOG (CHAPTER_LEARNING_ID);

/* =========================================================
   5. QUIZ 변경
   ========================================================= */

ALTER TABLE QUIZ ADD (
    UPDATED_AT DATE
);

/* 각 챕터당 퀴즈 정책: CHAPTER_ID 필수 */
ALTER TABLE QUIZ MODIFY CHAPTER_ID NOT NULL;

/* =========================================================
   6. QUIZ_ATTEMPT 변경
   ========================================================= */

ALTER TABLE QUIZ_ATTEMPT DROP CONSTRAINT UK_QUIZ_ATTEMPT_NO;
ALTER TABLE QUIZ_ATTEMPT DROP CONSTRAINT CK_QUIZ_ATTEMPT_PASS;
ALTER TABLE QUIZ_ATTEMPT DROP CONSTRAINT CK_QUIZ_ATTEMPT_SCORE;

ALTER TABLE QUIZ_ATTEMPT DROP COLUMN ATTEMPT_NO;
ALTER TABLE QUIZ_ATTEMPT DROP COLUMN SCORE;
ALTER TABLE QUIZ_ATTEMPT DROP COLUMN PASS_YN;

/* 각 챕터 퀴즈 응시는 챕터 기준이므로 필수 */
ALTER TABLE QUIZ_ATTEMPT MODIFY CHAPTER_ID NOT NULL;

ALTER TABLE QUIZ_ATTEMPT ADD CONSTRAINT UK_QUIZ_ATTEMPT
UNIQUE (USER_ID, COURSE_ID, CHAPTER_ID);

/* CHAPTER_LEARNING_STATUS.QUIZ_ATTEMPT_ID FK는 QUIZ_ATTEMPT 변경 후 추가 */
ALTER TABLE CHAPTER_LEARNING_STATUS ADD CONSTRAINT FK_CHAPTER_LEARNING_QUIZ_ATTEMPT
FOREIGN KEY (QUIZ_ATTEMPT_ID) REFERENCES QUIZ_ATTEMPT (ATTEMPT_ID);

/* =========================================================
   7. OFFLINE_COURSE 현재 신청 인원 캐시 컬럼 추가
   ========================================================= */

ALTER TABLE OFFLINE_COURSE ADD (
    CURRENT_APPLICANT_COUNT NUMBER DEFAULT 0 NOT NULL
);

ALTER TABLE OFFLINE_COURSE ADD CONSTRAINT CK_OFFLINE_CURRENT_APPLICANT_COUNT
CHECK (CURRENT_APPLICANT_COUNT >= 0);

/* 기존 APPROVED 신청 데이터를 기준으로 현재 신청 인원 초기화 */
UPDATE OFFLINE_COURSE oc
SET CURRENT_APPLICANT_COUNT = (
    SELECT COUNT(*)
    FROM COURSE_APPLICATION ca
    WHERE ca.COURSE_ID = oc.COURSE_ID
      AND ca.APPLICATION_STATUS = 'APPROVED'
);

/* =========================================================
   8. 강의 상세 상태값 정리: OPEN / CANCELED / HIDDEN
   ========================================================= */

UPDATE ONLINE_COURSE
SET STATUS = 'OPEN'
WHERE STATUS = 'ACTIVE';

UPDATE OFFLINE_COURSE
SET STATUS = 'OPEN'
WHERE STATUS = 'ACTIVE';

ALTER TABLE ONLINE_COURSE MODIFY STATUS DEFAULT 'OPEN';
ALTER TABLE OFFLINE_COURSE MODIFY STATUS DEFAULT 'OPEN';

ALTER TABLE ONLINE_COURSE ADD CONSTRAINT CK_ONLINE_COURSE_STATUS
CHECK (STATUS IN ('OPEN', 'CANCELED', 'HIDDEN'));

ALTER TABLE OFFLINE_COURSE ADD CONSTRAINT CK_OFFLINE_COURSE_STATUS
CHECK (STATUS IN ('OPEN', 'CANCELED', 'HIDDEN'));

COMMIT;
