/* =========================================================
   Flyway Migration: V2__alter_schema.sql
   Target DB       : Oracle
   Purpose         : Update learning/application/quiz schema

   Assumption
   - V1 has already created the original tables.
   - This migration changes the existing V1 schema to the revised ERD.
   - This file is intended for a development DB. If production data already
     exists, verify duplicate data before applying the new UNIQUE constraints.

   Main changes
   - COURSE_APPLICATION: add APPLICATION_TYPE, CANCELED_AT
   - COURSE_LEARNING_STATUS: rename LEARNING_ID -> COURSE_LEARNING_ID,
     rename LEARNING_STATUS -> STATUS, remove chapter-level play columns
   - CHAPTER_LEARNING_STATUS: create new chapter-level progress table
   - LEARNING_LOG: rename LEARNING_ID -> COURSE_LEARNING_ID,
     add CHAPTER_LEARNING_ID
   - QUIZ: add UPDATED_AT, make CHAPTER_ID required
   - QUIZ_ATTEMPT: remove ATTEMPT_NO/SCORE/PASS_YN,
     add UNIQUE(USER_ID, COURSE_ID, CHAPTER_ID)
   ========================================================= */

/* =========================
   1. COURSE_APPLICATION
   ========================= */
ALTER TABLE COURSE_APPLICATION ADD (
    APPLICATION_TYPE VARCHAR2(30) DEFAULT 'USER' NOT NULL,
    CANCELED_AT      DATE
);

/* =========================
   2. COURSE_LEARNING_STATUS
   ========================= */
/* Drop dependent FK/index from LEARNING_LOG before renaming the referenced column. */
ALTER TABLE LEARNING_LOG DROP CONSTRAINT FK_LOG_LEARNING;
DROP INDEX IX_LOG_LEARNING;

/* Remove old checks that depend on columns to be removed. */
ALTER TABLE COURSE_LEARNING_STATUS DROP CONSTRAINT CK_LAST_PLAY_SECONDS;

/* Rename course-level learning PK column and status column. */
ALTER TABLE COURSE_LEARNING_STATUS RENAME COLUMN LEARNING_ID TO COURSE_LEARNING_ID;
ALTER TABLE COURSE_LEARNING_STATUS RENAME COLUMN LEARNING_STATUS TO STATUS;

/* These are now managed per chapter in CHAPTER_LEARNING_STATUS. */
ALTER TABLE COURSE_LEARNING_STATUS DROP COLUMN LAST_PLAY_SECONDS;
ALTER TABLE COURSE_LEARNING_STATUS DROP COLUMN COMPLETION_STATUS;

ALTER TABLE COURSE_LEARNING_STATUS ADD (
    UPDATED_AT DATE
);

/* =========================
   3. LEARNING_LOG
   ========================= */
ALTER TABLE LEARNING_LOG RENAME COLUMN LEARNING_ID TO COURSE_LEARNING_ID;

ALTER TABLE LEARNING_LOG ADD (
    CHAPTER_LEARNING_ID NUMBER
);

ALTER TABLE LEARNING_LOG ADD CONSTRAINT FK_LOG_COURSE_LEARNING
    FOREIGN KEY (COURSE_LEARNING_ID)
    REFERENCES COURSE_LEARNING_STATUS (COURSE_LEARNING_ID);

/* =========================
   4. QUIZ
   ========================= */
ALTER TABLE QUIZ ADD (
    UPDATED_AT DATE
);

/* Revised ERD recommends quiz per chapter. This will fail if existing QUIZ.CHAPTER_ID has NULL rows. */
ALTER TABLE QUIZ MODIFY (CHAPTER_ID NOT NULL);

/* =========================
   5. QUIZ_ATTEMPT
   ========================= */
/* Existing V1 allowed multiple attempts through ATTEMPT_NO. Revised ERD allows one attempt per user/course/chapter. */
ALTER TABLE QUIZ_ATTEMPT DROP CONSTRAINT UK_QUIZ_ATTEMPT_NO;
ALTER TABLE QUIZ_ATTEMPT DROP CONSTRAINT CK_QUIZ_ATTEMPT_PASS;
ALTER TABLE QUIZ_ATTEMPT DROP CONSTRAINT CK_QUIZ_ATTEMPT_SCORE;

ALTER TABLE QUIZ_ATTEMPT DROP COLUMN ATTEMPT_NO;
ALTER TABLE QUIZ_ATTEMPT DROP COLUMN SCORE;
ALTER TABLE QUIZ_ATTEMPT DROP COLUMN PASS_YN;

/* Revised ERD treats CHAPTER_ID as part of the required unique key. */
ALTER TABLE QUIZ_ATTEMPT MODIFY (CHAPTER_ID NOT NULL);

ALTER TABLE QUIZ_ATTEMPT ADD CONSTRAINT UK_QA_U_C_CH
    UNIQUE (USER_ID, COURSE_ID, CHAPTER_ID);

/* =========================
   6. CHAPTER_LEARNING_STATUS
   ========================= */
CREATE SEQUENCE CHAPTER_LEARNING_STATUS_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE CHAPTER_LEARNING_STATUS (
    CHAPTER_LEARNING_ID NUMBER       NOT NULL,
    COURSE_LEARNING_ID  NUMBER       NOT NULL,
    USER_ID             NUMBER       NOT NULL,
    COURSE_ID           NUMBER       NOT NULL,
    CHAPTER_ID          NUMBER       NOT NULL,
    PROGRESS_RATE       NUMBER       DEFAULT 0 NOT NULL,
    LAST_PLAY_SECONDS   NUMBER       DEFAULT 0 NOT NULL,
    MAX_PLAY_SECONDS    NUMBER       DEFAULT 0 NOT NULL,
    QUIZ_ATTEMPT_ID     NUMBER,
    STATUS              VARCHAR2(30) DEFAULT 'NOT_STARTED' NOT NULL,
    STARTED_AT          DATE,
    COMPLETED_AT        DATE,
    UPDATED_AT          DATE,
    CONSTRAINT PK_CHAPTER_LEARNING PRIMARY KEY (CHAPTER_LEARNING_ID),
    CONSTRAINT UK_CHLS_CL_CHAPTER UNIQUE (COURSE_LEARNING_ID, CHAPTER_ID),
    CONSTRAINT UK_CHLS_QUIZ_ATTEMPT UNIQUE (QUIZ_ATTEMPT_ID),
    CONSTRAINT CK_CHLS_PROGRESS CHECK (PROGRESS_RATE BETWEEN 0 AND 100),
    CONSTRAINT CK_CHLS_LAST_SECONDS CHECK (LAST_PLAY_SECONDS >= 0),
    CONSTRAINT CK_CHLS_MAX_SECONDS CHECK (MAX_PLAY_SECONDS >= 0)
);

ALTER TABLE CHAPTER_LEARNING_STATUS ADD CONSTRAINT FK_CHLS_CLS
    FOREIGN KEY (COURSE_LEARNING_ID)
    REFERENCES COURSE_LEARNING_STATUS (COURSE_LEARNING_ID);

ALTER TABLE CHAPTER_LEARNING_STATUS ADD CONSTRAINT FK_CHLS_USER
    FOREIGN KEY (USER_ID)
    REFERENCES USERS (USER_ID);

ALTER TABLE CHAPTER_LEARNING_STATUS ADD CONSTRAINT FK_CHLS_COURSE
    FOREIGN KEY (COURSE_ID)
    REFERENCES COURSE (COURSE_ID);

ALTER TABLE CHAPTER_LEARNING_STATUS ADD CONSTRAINT FK_CHLS_CHAPTER
    FOREIGN KEY (CHAPTER_ID)
    REFERENCES COURSE_CHAPTER (CHAPTER_ID);

ALTER TABLE CHAPTER_LEARNING_STATUS ADD CONSTRAINT FK_CHLS_QUIZ_ATTEMPT
    FOREIGN KEY (QUIZ_ATTEMPT_ID)
    REFERENCES QUIZ_ATTEMPT (ATTEMPT_ID);

/* LEARNING_LOG now can reference chapter-level learning status. */
ALTER TABLE LEARNING_LOG ADD CONSTRAINT FK_LOG_CHAPTER_LEARNING
    FOREIGN KEY (CHAPTER_LEARNING_ID)
    REFERENCES CHAPTER_LEARNING_STATUS (CHAPTER_LEARNING_ID);

/* =========================
   7. INDEXES
   ========================= */
CREATE INDEX IX_LOG_COURSE_LEARNING ON LEARNING_LOG (COURSE_LEARNING_ID);
CREATE INDEX IX_LOG_CHAPTER_LEARNING ON LEARNING_LOG (CHAPTER_LEARNING_ID);

CREATE INDEX IX_CHLS_COURSE_LEARNING ON CHAPTER_LEARNING_STATUS (COURSE_LEARNING_ID);
CREATE INDEX IX_CHLS_USER ON CHAPTER_LEARNING_STATUS (USER_ID);
CREATE INDEX IX_CHLS_COURSE ON CHAPTER_LEARNING_STATUS (COURSE_ID);
CREATE INDEX IX_CHLS_CHAPTER ON CHAPTER_LEARNING_STATUS (CHAPTER_ID);
/* UK_CHLS_QUIZ_ATTEMPT and UK_QA_U_C_CH already create supporting unique indexes. */
