/* V6__add_level_test_build_status.sql */

ALTER TABLE CAREER_DIAGNOSIS ADD (
    LEVEL_TEST_BUILD_STATUS VARCHAR2(30) DEFAULT 'PENDING' NOT NULL
);

ALTER TABLE CAREER_DIAGNOSIS
    ADD CONSTRAINT CK_LEVEL_TEST_BUILD_STATUS
        CHECK (LEVEL_TEST_BUILD_STATUS IN (
            'PENDING',
            'PROCESSING',
            'COMPLETED',
            'FAILED'
        ));

COMMIT;
