ALTER TABLE CHAPTER_SKILL ADD (
    COVERAGE_LEVEL  VARCHAR2(30),
    COVERAGE_REASON VARCHAR2(1000)
);

ALTER TABLE COURSE_SKILL ADD (
    COVERAGE_LEVEL  VARCHAR2(30),
    COVERAGE_REASON VARCHAR2(1000)
);

ALTER TABLE CAREER_TARGET_SKILL ADD (
    USER_SET_SKILL_LEVEL VARCHAR2(30)
);
