ALTER TABLE COMPETENCY_SCORE_HISTORY
DROP COLUMN CALC_REASON;

ALTER TABLE COMPETENCY_SCORE_HISTORY
ADD CALC_TYPE VARCHAR2(50) DEFAULT 'UNKNOWN' NOT NULL;

ALTER TABLE SKILL
ADD SKILL_CODE VARCHAR2(100);

ALTER TABLE SKILL ADD CONSTRAINT UK_SKILL_CODE UNIQUE (SKILL_CODE);

CREATE SEQUENCE COMP_ACTION_SCORE_POLICY_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SKILL_COMPETENCY_SCORE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE COMPETENCY_ACTION_SCORE_POLICY (
    POLICY_ID     NUMBER       NOT NULL,
    CALC_TYPE     VARCHAR2(50) NOT NULL,
    COMPETENCY_ID NUMBER       NOT NULL,
    SCORE_DELTA   NUMBER(5, 2) NOT NULL,
    USE_YN        VARCHAR2(1)  DEFAULT 'Y' NOT NULL,
    CREATED_AT    DATE         DEFAULT SYSDATE NOT NULL,
    UPDATED_AT    DATE,
    CONSTRAINT PK_COMP_ACTION_SCORE_POLICY PRIMARY KEY (POLICY_ID),
    CONSTRAINT UK_COMP_ACTION_SCORE_POLICY UNIQUE (CALC_TYPE, COMPETENCY_ID),
    CONSTRAINT CK_COMP_ACTION_POLICY_USE_YN CHECK (USE_YN IN ('Y', 'N')),
    CONSTRAINT CK_COMP_ACTION_POLICY_SCORE CHECK (SCORE_DELTA > 0)
);

CREATE TABLE SKILL_COMPETENCY_SCORE (
    POLICY_ID     NUMBER       NOT NULL,
    SKILL_ID      NUMBER       NOT NULL,
    CALC_TYPE     VARCHAR2(50) NOT NULL,
    COMPETENCY_ID NUMBER       NOT NULL,
    SCORE_DELTA   NUMBER(5, 2) NOT NULL,
    USE_YN        VARCHAR2(1)  DEFAULT 'Y' NOT NULL,
    CREATED_AT    DATE         DEFAULT SYSDATE NOT NULL,
    UPDATED_AT    DATE,
    CONSTRAINT PK_SKILL_COMPETENCY_SCORE PRIMARY KEY (POLICY_ID),
    CONSTRAINT UK_SKILL_COMPETENCY_SCORE UNIQUE (SKILL_ID, CALC_TYPE, COMPETENCY_ID),
    CONSTRAINT CK_SKILL_COMP_SCORE_USE_YN CHECK (USE_YN IN ('Y', 'N')),
    CONSTRAINT CK_SKILL_COMP_SCORE_DELTA CHECK (SCORE_DELTA > 0)
);

ALTER TABLE COMPETENCY_ACTION_SCORE_POLICY ADD CONSTRAINT FK_COMP_ACTION_POLICY_COMP
    FOREIGN KEY (COMPETENCY_ID) REFERENCES COMPETENCY (COMPETENCY_ID);

ALTER TABLE SKILL_COMPETENCY_SCORE ADD CONSTRAINT FK_SKILL_COMP_SCORE_SKILL
    FOREIGN KEY (SKILL_ID) REFERENCES SKILL (SKILL_ID);

ALTER TABLE SKILL_COMPETENCY_SCORE ADD CONSTRAINT FK_SKILL_COMP_SCORE_COMP
    FOREIGN KEY (COMPETENCY_ID) REFERENCES COMPETENCY (COMPETENCY_ID);

CREATE INDEX IX_COMP_ACTION_POLICY_TYPE ON COMPETENCY_ACTION_SCORE_POLICY (CALC_TYPE, USE_YN);
CREATE INDEX IX_SKILL_COMP_SCORE_SKILL ON SKILL_COMPETENCY_SCORE (SKILL_ID, USE_YN);
CREATE INDEX IX_SKILL_COMP_SCORE_TYPE ON SKILL_COMPETENCY_SCORE (CALC_TYPE, USE_YN);

INSERT INTO COMPETENCY_ACTION_SCORE_POLICY (
    POLICY_ID,
    CALC_TYPE,
    COMPETENCY_ID,
    SCORE_DELTA
)
SELECT COMP_ACTION_SCORE_POLICY_SEQ.NEXTVAL, 'QUIZ_PERFECT', 1, 0.5
FROM COMPETENCY
WHERE COMPETENCY_ID = 1;

INSERT INTO COMPETENCY_ACTION_SCORE_POLICY (
    POLICY_ID,
    CALC_TYPE,
    COMPETENCY_ID,
    SCORE_DELTA
)
SELECT COMP_ACTION_SCORE_POLICY_SEQ.NEXTVAL, 'LEVEL_TEST_TAKEN', 2, 0.8
FROM COMPETENCY
WHERE COMPETENCY_ID = 2;

INSERT INTO COMPETENCY_ACTION_SCORE_POLICY (
    POLICY_ID,
    CALC_TYPE,
    COMPETENCY_ID,
    SCORE_DELTA
)
SELECT COMP_ACTION_SCORE_POLICY_SEQ.NEXTVAL, 'STREAK_7', 2, 0.8
FROM COMPETENCY
WHERE COMPETENCY_ID = 2;

INSERT INTO COMPETENCY_ACTION_SCORE_POLICY (
    POLICY_ID,
    CALC_TYPE,
    COMPETENCY_ID,
    SCORE_DELTA
)
SELECT COMP_ACTION_SCORE_POLICY_SEQ.NEXTVAL, 'STREAK_30', 2, 1.5
FROM COMPETENCY
WHERE COMPETENCY_ID = 2;

INSERT INTO COMPETENCY_ACTION_SCORE_POLICY (
    POLICY_ID,
    CALC_TYPE,
    COMPETENCY_ID,
    SCORE_DELTA
)
SELECT COMP_ACTION_SCORE_POLICY_SEQ.NEXTVAL, 'RECOMMENDED_COURSE_COMPLETE', 2, 1.0
FROM COMPETENCY
WHERE COMPETENCY_ID = 2;

INSERT INTO COMPETENCY_ACTION_SCORE_POLICY (
    POLICY_ID,
    CALC_TYPE,
    COMPETENCY_ID,
    SCORE_DELTA
)
SELECT COMP_ACTION_SCORE_POLICY_SEQ.NEXTVAL, 'FIRST_SKILL_LEARNING', 2, 1.0
FROM COMPETENCY
WHERE COMPETENCY_ID = 2;

INSERT INTO COMPETENCY_ACTION_SCORE_POLICY (
    POLICY_ID,
    CALC_TYPE,
    COMPETENCY_ID,
    SCORE_DELTA
)
SELECT COMP_ACTION_SCORE_POLICY_SEQ.NEXTVAL, 'KCY_MATCH_REQUEST', 3, 1.0
FROM COMPETENCY
WHERE COMPETENCY_ID = 3;

INSERT INTO COMPETENCY_ACTION_SCORE_POLICY (
    POLICY_ID,
    CALC_TYPE,
    COMPETENCY_ID,
    SCORE_DELTA
)
SELECT COMP_ACTION_SCORE_POLICY_SEQ.NEXTVAL, 'GLOBAL_NEWS_CLICK', 6, 0.2
FROM COMPETENCY
WHERE COMPETENCY_ID = 6;

INSERT INTO COMPETENCY_ACTION_SCORE_POLICY (
    POLICY_ID,
    CALC_TYPE,
    COMPETENCY_ID,
    SCORE_DELTA
)
SELECT COMP_ACTION_SCORE_POLICY_SEQ.NEXTVAL, 'LANGUAGE_SCORE_REGISTERED', 6, 1.0
FROM COMPETENCY
WHERE COMPETENCY_ID = 6;
