CREATE SEQUENCE KCY_COFFEE_CHAT_REQUEST_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE MAIL_SEND_LOG_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE USER_COFFEE_CHAT_SETTING (
    USER_ID         NUMBER      NOT NULL,
    EMAIL_NOTIFY_YN VARCHAR2(1) DEFAULT 'N' NOT NULL,
    CREATED_AT      DATE        DEFAULT SYSDATE NOT NULL,
    UPDATED_AT      DATE,
    CONSTRAINT PK_USER_COFFEE_CHAT_SETTING PRIMARY KEY (USER_ID),
    CONSTRAINT CK_USER_COFFEE_CHAT_NOTIFY CHECK (EMAIL_NOTIFY_YN IN ('Y', 'N'))
);

CREATE TABLE KCY_COFFEE_CHAT_REQUEST (
    COFFEE_CHAT_REQUEST_ID NUMBER        NOT NULL,
    REQUESTER_USER_ID      NUMBER        NOT NULL,
    RECEIVER_USER_ID       NUMBER        NOT NULL,
    REQUESTER_KCY_CODE     VARCHAR2(20),
    RECEIVER_KCY_CODE      VARCHAR2(20),
    MATCH_GRADE            VARCHAR2(10),
    MESSAGE                VARCHAR2(1000),
    STATUS                 VARCHAR2(30)  DEFAULT 'REQUESTED' NOT NULL,
    CREATED_AT             DATE          DEFAULT SYSDATE NOT NULL,
    UPDATED_AT             DATE,
    CONSTRAINT PK_KCY_COFFEE_CHAT_REQUEST PRIMARY KEY (COFFEE_CHAT_REQUEST_ID),
    CONSTRAINT CK_KCY_COFFEE_CHAT_STATUS CHECK (STATUS IN ('REQUESTED', 'ACCEPTED', 'REJECTED', 'CANCELED'))
);

CREATE TABLE MAIL_SEND_LOG (
    MAIL_LOG_ID    NUMBER        NOT NULL,
    REQUEST_ID     NUMBER,
    RECEIVER_USER_ID NUMBER,
    TO_EMAIL       VARCHAR2(255),
    SUBJECT        VARCHAR2(255) NOT NULL,
    CONTENT        CLOB,
    SEND_STATUS    VARCHAR2(30)  DEFAULT 'PENDING' NOT NULL,
    ERROR_MESSAGE  VARCHAR2(1000),
    CREATED_AT     DATE          DEFAULT SYSDATE NOT NULL,
    SENT_AT        DATE,
    CONSTRAINT PK_MAIL_SEND_LOG PRIMARY KEY (MAIL_LOG_ID),
    CONSTRAINT CK_MAIL_SEND_LOG_STATUS CHECK (SEND_STATUS IN ('PENDING', 'SENT', 'FAILED', 'SKIPPED'))
);

ALTER TABLE USER_COFFEE_CHAT_SETTING ADD CONSTRAINT FK_COFFEE_CHAT_SETTING_USER
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID);

ALTER TABLE KCY_COFFEE_CHAT_REQUEST ADD CONSTRAINT FK_COFFEE_CHAT_REQUESTER
    FOREIGN KEY (REQUESTER_USER_ID) REFERENCES USERS(USER_ID);

ALTER TABLE KCY_COFFEE_CHAT_REQUEST ADD CONSTRAINT FK_COFFEE_CHAT_RECEIVER
    FOREIGN KEY (RECEIVER_USER_ID) REFERENCES USERS(USER_ID);

ALTER TABLE MAIL_SEND_LOG ADD CONSTRAINT FK_MAIL_SEND_LOG_REQUEST
    FOREIGN KEY (REQUEST_ID) REFERENCES KCY_COFFEE_CHAT_REQUEST(COFFEE_CHAT_REQUEST_ID);

ALTER TABLE MAIL_SEND_LOG ADD CONSTRAINT FK_MAIL_SEND_LOG_RECEIVER
    FOREIGN KEY (RECEIVER_USER_ID) REFERENCES USERS(USER_ID);
